language: node_js
node_js:
  - '12'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm install -g lerna
  - npm install -g greenkeeper-lockfile
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

install:
  - yarn cache clean
  - yarn install
  - yarn bootstrap
  - yarn build

script:
  - yarn run test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - NODE_DEBUG=gh-pages multi-semantic-release
